version: '3.0'

services:
  springboot:
    container_name: springboot
    ports: 
      - '8081:8081'
    volumes:
      - springboot_data:/var/lib/springboot
    networks:
      - appnet
    command: sh -c 'if [ -e /app.jar ]; then java -jar /app.jar --spring.profiles.active=production; else echo "app.jar not found, skipping execution"; fi'
    image: openjdk:21    
    
  mysql:
    container_name: mysql
    ports: 
      - '13306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks: 
      - appnet
    env_file: .env.prod
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  
    image: mysql:8.0.34
   
volumes:
  mysql_data: {}
  springboot_data: {}

networks:
    jenkinsnet: {}
    appnet: {}