version: "3"
services:
  bibibig-mysql:
    container_name: bibibig-mysql
    build:
      dockerfile: Dockerfile
      context: ./database
    image: xntm10/bibibig-mysql
    volumes:
      # 설정파일 저장될  위치
      - ./database/config:/etc/mysql/conf.d
      # DB 데이터 저장 디렉토리
      - ./database/data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - "TZ=Asia/Seoul"
    ports:
      - "3306:3306"